spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jwt_security3
    username: root
    password: 12123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
